export const SET_COORDINATE = 'SET_COORDINATE';
export const SET_RADIUS = 'SET_RADIUS';

export const GET_NEARBY_HOSPITALS_REQUEST = 'GET_NEARBY_HOSPITALS_REQUEST';
export const GET_NEARBY_HOSPITALS_SUCCESS = 'GET_NEARBY_HOSPITALS_SUCCESS';
export const GET_NEARBY_HOSPITALS_FAILED = 'GET_NEARBY_HOSPITALS_FAILED';
